#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Author: 臧成龙
@Contact: 939589097@qq.com
@Time: 2025-12-31
@File: settings.py
@Desc: Django settings for application project. - 
"""
"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from env import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 从环境变量读取，如果没有则使用默认值，但生产环境必须设置
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-y(df$uwnha$0nrkmh5g(ri^=^#3qru3bf8$pw+t6e_wb*op7gj')

# 生产环境检查 SECRET_KEY
if SECRET_KEY == 'django-insecure-y(df$uwnha$0nrkmh5g(ri^=^#3qru3bf8$pw+t6e_wb*op7gj' and not DEBUG:
    raise ValueError("DJANGO_SECRET_KEY must be set in production environment")

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'channels',  # WebSocket支持
    'core',
    'scheduler',
]

MIDDLEWARE = [
    'common.middleware.CorsMiddleware',
    'common.middleware.ClientLicenseGateMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'common.middleware.SecurityHeadersMiddleware',  # 新增安全头中间件
    # 'common.middleware.ApiLoggingMiddleware',
]

# env 模块可覆盖（client 模式使用 application.client_urls）
if 'ROOT_URLCONF' not in globals():
    ROOT_URLCONF = 'application.urls'
AUTH_USER_MODEL = 'core.User'

WSGI_APPLICATION = 'application.wsgi.application'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 数据库配置
if DATABASE_TYPE == "MYSQL":
    # Mysql数据库
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "NAME": DATABASE_NAME,
        }
    }
elif DATABASE_TYPE == "SQLSERVER":
    # SqlServer数据库
    DATABASES = {
        "default": {
            "ENGINE": "mssql",
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "NAME": DATABASE_NAME,
            # 全局开启事务，绑定的是http请求响应整个过程
            'ATOMIC_REQUESTS': True,
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
            },
        }
    }
elif DATABASE_TYPE == "POSTGRESQL":
    # POSTGRESQL
    DATABASES = {
        "default": {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "NAME": DATABASE_NAME,
            # 全局开启事务，绑定的是http请求响应整个过程
            'ATOMIC_REQUESTS': True,
        },
    }
else:
    # sqlite3 数据库（standalone 可通过 DATABASE_SQLITE_PATH 指定路径）
    _sqlite_path = globals().get('DATABASE_SQLITE_PATH') or os.path.join(BASE_DIR, 'db.sqlite3')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _sqlite_path,
            'OPTIONS': {
                # timeout 映射到 sqlite busy_timeout（被锁时最多等 20s 再报错）
                'timeout': 20,
                # 多账号托管：API 进程与 Worker 进程并发读写同一库文件。
                # WAL 让读不阻塞写、写不阻塞读，大幅减少 database is locked；
                # synchronous=NORMAL 在 WAL 下兼顾安全与吞吐；foreign_keys 与默认一致。
                'init_command': (
                    'PRAGMA journal_mode=WAL;'
                    'PRAGMA synchronous=NORMAL;'
                    'PRAGMA foreign_keys=ON;'
                    'PRAGMA busy_timeout=20000;'
                ),
                # 写事务开启即取写锁（BEGIN IMMEDIATE），避免延迟升级锁导致的死锁/locked。
                'transaction_mode': 'IMMEDIATE',
            },
        }
    }

# 数据库路由器配置
# DATABASE_ROUTERS = ['application.db_router.DatabaseRouter']

# 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f'{REDIS_URL}/{REDIS_DB}',
        "TIMEOUT": None,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}

# # ================================================= #
# # ********************* 日志配置 ******************* #
# # ================================================= #

if ENV == 'client':
    LOGS_FILE = os.path.dirname(SERVER_LOGS_FILE)
else:
    SERVER_LOGS_FILE = os.path.join(BASE_DIR, "logs", "server.log")
    ERROR_LOGS_FILE = os.path.join(BASE_DIR, "logs", "error.log")
    LOGS_FILE = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOGS_FILE):
    os.makedirs(LOGS_FILE, exist_ok=True)

# 格式:[2020-04-22 23:33:01][micoservice.apps.ready():16] [INFO] 这是一条日志:
# 格式:[日期][模块.函数名称():行号] [级别] 信息
STANDARD_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
CONSOLE_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": STANDARD_LOG_FORMAT},
        "console": {
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "file": {
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": SERVER_LOGS_FILE,
            "when": "midnight",
            "interval": 1,
            "backupCount": 30,
            "formatter": "standard",
            "encoding": "utf-8",
            "utc": False,
        },
        "error": {
            "level": "ERROR",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": ERROR_LOGS_FILE,
            "when": "midnight",
            "interval": 1,
            "backupCount": 30,
            "formatter": "standard",
            "encoding": "utf-8",
            "utc": False,
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "console",
        },

    },
    "loggers": {
        "": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
            "propagate": False,
        },
        'django.db.backends': {
            'handlers': ["console", "error", "file"],
            'propagate': False,
            'level': "INFO"
        },
        "uvicorn.error": {
            "level": "INFO",
            "handlers": ["console", "error", "file"],
        },
        "uvicorn.access": {
            "handlers": ["console", "error", "file"],
            "level": "INFO"
        },
    },
}

if ENV == 'client':
    LOGGING['handlers']['file']['filename'] = SERVER_LOGS_FILE
    LOGGING['handlers']['error']['filename'] = ERROR_LOGS_FILE

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# # ================================================= #
# # ******************** Celery 配置 ***************** #
# # ================================================= #
CELERY_BROKER_URL = f'{REDIS_URL}/2'
DJANGO_CELERY_BEAT_TZ_AWARE = False
CELERY_ENABLE_UTC = False
CELERY_WORKER_CONCURRENCY = 2  # 并发数
CELERY_MAX_TASKS_PER_CHILD = 5  # 没个worker最多执行5个任务便自我销毁释放内存
CELERY_TIMEZONE = TIME_ZONE  # celery 时区问题
CELERY_RESULT_BACKEND = 'django-db'  # celery结果存储到数据库中

# # ================================================= #
# # ******************** JWT 配置 ***************** #
# # ================================================= #

# 生产环境验证密钥已配置
if not DEBUG:
    if JWT_ACCESS_SECRET_KEY == 'default-access-secret-key-change-in-production':
        raise ValueError("JWT_ACCESS_SECRET_KEY must be set in production environment")
    if JWT_REFRESH_SECRET_KEY == 'default-refresh-secret-key-change-in-production':
        raise ValueError("JWT_REFRESH_SECRET_KEY must be set in production environment")

JWT_ALGORITHM = "HS256"
# 修复：缩短 token 过期时间
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.environ.get('JWT_ACCESS_TOKEN_EXPIRE_MINUTES', 60 * 24))  # 默认1小时
JWT_REFRESH_TOKEN_EXPIRE_MINUTES = int(os.environ.get('JWT_REFRESH_TOKEN_EXPIRE_MINUTES', 60 * 24 * 7))  # 默认7天

# # ================================================= #
# # ******************** 邮箱 配置 ***************** #
# # ================================================= #

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'  # 邮件服务器地址
EMAIL_PORT = 25  # 邮件服务器端口
EMAIL_USE_TLS = False  # 是否使用 TLS
EMAIL_HOST_USER = ''  # 发件人邮箱
EMAIL_HOST_PASSWORD = ''  # 发件人邮箱密码

# 接口白名单，不需要授权直接访问 - 修复：缩小范围
API_WHITE_LIST = [
    '/api/core/userinfo',
    '/api/core/menu/route/tree'
]

API_LOG_ENABLE = False
ENABLE_LOGIN_ANALYSIS_LOG = False
API_LOG_METHODS = ['POST', 'GET', 'DELETE', 'PUT']
API_MODEL_MAP = {}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # ================================================= #
# # ******************** 安全配置 ***************** #
# # ================================================= #

# HTTPS 和安全头配置
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# SameSite Cookie
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_SAMESITE = 'Strict'

# 安全 HTTP 头
SECURE_HSTS_SECONDS = 31536000  # 1年
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# 防止内容类型嗅探
SECURE_CONTENT_TYPE_NOSNIFF = True

# 点击劫持防护
X_FRAME_OPTIONS = 'DENY'

# ================================================= #
# ********************* 文件存储配置 ******************* #
# ================================================= #

# 文件存储类型: local, oss, minio, azure（生产 Docker 默认 local）
FILE_STORAGE_TYPE = os.environ.get('FILE_STORAGE_TYPE', 'local')

# 本地存储配置
FILE_STORAGE_LOCAL_PATH = os.path.join(BASE_DIR, 'media', 'file_manager')

# 阿里云OSS配置
OSS_ENDPOINT = ''
OSS_ACCESS_KEY_ID = ''
OSS_ACCESS_KEY_SECRET = ''
OSS_BUCKET_NAME = ''

# Minio配置
MINIO_ENDPOINT = os.environ.get('MINIO_ENDPOINT', 'minio_endpoint')
MINIO_ACCESS_KEY = os.environ.get('MINIO_ACCESS_KEY', 'minio_access_key')
MINIO_SECRET_KEY = os.environ.get('MINIO_SECRET_KEY', 'minio_secret_key')
MINIO_BUCKET_NAME = os.environ.get('MINIO_BUCKET_NAME', 'minio_bucket_name')

# Azure Blob配置
AZURE_ACCOUNT_NAME = ''
AZURE_ACCOUNT_KEY = ''
AZURE_CONTAINER_NAME = ''

# ================================================= #
# ********************* AAD配置 ******************* #
# ================================================= #

# Azure AD 租户ID
AAD_TENANT_ID = ''

# Azure AD 应用程序(客户端) ID
AAD_CLIENT_ID = ''

# 如果需要验证特定的租户，可以设置为具体的租户ID
# AAD_TENANT_ID = 'your-tenant-id'


# ============前端版本 v5为Vben V5，v2位Vben2================== #

# ================================================= #
# ********************* Channels WebSocket配置 ******************* #
# ================================================= #

# ASGI 应用程序
ASGI_APPLICATION = 'application.asgi.application'

# Channels 层配置（client/standalone 在 env 模块已设为 InMemoryChannelLayer）
if 'CHANNEL_LAYERS' not in globals():
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:6379/{REDIS_DB}"],
                "symmetric_encryption_keys": [SECRET_KEY],
            },
        },
    }

DEFAULT_PASSWORD = "123456"

# ================================================= #
# ********************* 阿里云短信服务配置 ******************* #
# ================================================= #

# 阿里云短信服务配置
ALIYUN_SMS_ACCESS_KEY_ID = ""  # 请填入您的AccessKey ID
ALIYUN_SMS_ACCESS_KEY_SECRET = ""  # 请填入您的AccessKey Secret
ALIYUN_SMS_SIGN_NAME = ""  # 请填入您的短信签名
ALIYUN_SMS_TEMPLATE_CODE = ""  # 验证码短信模板代码
ALIYUN_SMS_NOTIFY_TEMPLATE_CODE = ""  # 通知短信模板代码，模板变量: ${title} ${content}

# ================================================= #
# ********************* 企业微信配置 ******************* #
# ================================================= #
WECOM_CORP_ID = ""  # 企业ID
WECOM_AGENT_ID = ""  # 应用AgentId
WECOM_SECRET = ""  # 应用Secret

# ================================================= #
# ********************* 钉钉配置 ******************* #
# ================================================= #
DINGTALK_APP_KEY = ""  # 应用AppKey
DINGTALK_APP_SECRET = ""  # 应用AppSecret
DINGTALK_AGENT_ID = ""  # 应用AgentId

# ================================================= #
# ********************* 飞书配置 ******************* #
# ================================================= #
FEISHU_APP_ID = ""  # 应用App ID
FEISHU_APP_SECRET = ""  # 应用App Secret

# ================================================= #
# ********************* 前端地址配置 ******************* #
# ================================================= #
FRONTEND_URL = "http://localhost:5555"  # 前端地址，用于消息跳转链接

# ================================================= #
# **************** 对外下载落地页配置 **************** #
# ================================================= #
# 根路径 / 的公开下载页所用链接。安装包/插件托管在独立的「公开」下载仓库，
# 主仓库私有不影响外部下载。可被环境变量覆盖（换仓库/换资源名时无需改代码）。
DOWNLOAD_DIST_REPO = os.environ.get('DOWNLOAD_DIST_REPO', 'lukylong/DyAuthReply-dist')
DOWNLOAD_RELEASE_PAGE = os.environ.get(
    'DOWNLOAD_RELEASE_PAGE', f'https://github.com/{DOWNLOAD_DIST_REPO}/releases/latest'
)

# 安装包/插件文件名（自托管与 GitHub 公开仓保持同名，换源只改前缀）
DOWNLOAD_MACOS_FILE = os.environ.get('DOWNLOAD_MACOS_FILE', 'DAssistant-macos-aarch64.dmg')
DOWNLOAD_WINDOWS_FILE = os.environ.get('DOWNLOAD_WINDOWS_FILE', 'DAssistant-windows-x64-setup.exe')
DOWNLOAD_EXTENSION_FILE = os.environ.get('DOWNLOAD_EXTENSION_FILE', 'douyin-cred-extractor.zip')

# 自建服务器托管（国内直连，规避 GitHub 慢）：
# 设置 DOWNLOAD_PUBLIC_BASE_URL（如 https://pro.zhenyangtang.com.cn）后，下载链接走
# 自己的 /downloads/ 目录；留空则回退到 GitHub 公开仓 releases/latest/download。
DOWNLOAD_PUBLIC_BASE_URL = os.environ.get('DOWNLOAD_PUBLIC_BASE_URL', '').rstrip('/')
# 安装包在服务器上的物理目录（建议挂载为持久化卷；nginx 也可直接 alias 此目录加速）
DOWNLOAD_LOCAL_DIR = os.environ.get('DOWNLOAD_LOCAL_DIR', '/var/lib/zq-platform/downloads')
# 可选：nginx X-Accel 直出加速。设为 nginx 内部 location（如 /_dl_internal）后，
# /downloads/ 的字节流由 nginx sendfile 直出（支持断点续传），Django 仅发头并保留
# 带版本号的下载文件名；留空则 Django 自己读盘返回。需在 nginx 配 internal location。
DOWNLOAD_XACCEL_LOCATION = os.environ.get('DOWNLOAD_XACCEL_LOCATION', '').strip()

if DOWNLOAD_PUBLIC_BASE_URL:
    _dl_base = f'{DOWNLOAD_PUBLIC_BASE_URL}/downloads'
else:
    _dl_base = os.environ.get(
        'DOWNLOAD_BASE_URL', f'https://github.com/{DOWNLOAD_DIST_REPO}/releases/latest/download'
    )

DOWNLOAD_MACOS_URL = os.environ.get('DOWNLOAD_MACOS_URL', f"{_dl_base}/{DOWNLOAD_MACOS_FILE}")
DOWNLOAD_WINDOWS_URL = os.environ.get('DOWNLOAD_WINDOWS_URL', f"{_dl_base}/{DOWNLOAD_WINDOWS_FILE}")
DOWNLOAD_EXTENSION_URL = os.environ.get('DOWNLOAD_EXTENSION_URL', f"{_dl_base}/{DOWNLOAD_EXTENSION_FILE}")
# 管理后台入口（落地页提供跳转）
DOWNLOAD_CONSOLE_URL = os.environ.get('DOWNLOAD_CONSOLE_URL', '/manage/')

# ================================================= #
# **************** 客户端升级通道配置 **************** #
# ================================================= #
# 客户端「检查更新」请求服务端 /api/client-auth/app-version 获取最新版本信息。
# 每次发版后更新 DOWNLOAD_LATEST_VERSION（或用环境变量覆盖），客户端据此提示升级。
DOWNLOAD_LATEST_VERSION = os.environ.get('DOWNLOAD_LATEST_VERSION') or '0.1.11'
# 是否强制更新（true 时客户端弹窗不提供「稍后」）
DOWNLOAD_FORCE_UPDATE = os.environ.get('DOWNLOAD_FORCE_UPDATE', 'false').lower() == 'true'
# 更新说明（支持用 \n 分隔多行）
DOWNLOAD_RELEASE_NOTES = os.environ.get(
    'DOWNLOAD_RELEASE_NOTES',
    '修复 Windows 全新安装时数据库迁移因控制台编码（GBK）崩溃导致启动失败\n'
    '新增单实例守卫：重复启动只唤回已有窗口，避免端口占用启动失败\n'
    '新增客户端在线检查更新通道\n'
    '修复私信工作台消息时间显示与排序问题\n'
    '优化多账号托管性能与稳定性',
)
