# Generated by Django 5.2.7 on 2026-04-23 17:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_seed_douyin_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerJob',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(db_index=True, help_text='任务名称', max_length=128)),
                ('code', models.CharField(db_index=True, help_text='任务编码', max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='任务编码只能包含字母、数字和下划线', regex='^[a-zA-Z0-9_]+$')])),
                ('description', models.TextField(blank=True, help_text='任务描述', null=True)),
                ('group', models.CharField(db_index=True, default='default', help_text='任务分组', max_length=64)),
                ('trigger_type', models.CharField(choices=[('cron', 'Cron表达式'), ('interval', '间隔执行'), ('date', '指定时间')], db_index=True, default='cron', help_text='触发器类型', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='Cron表达式（如：0 0 * * *）', max_length=128, null=True)),
                ('interval_seconds', models.IntegerField(blank=True, help_text='间隔时间（秒）', null=True)),
                ('run_date', models.DateTimeField(blank=True, help_text='指定执行时间', null=True)),
                ('task_func', models.CharField(help_text='任务函数路径', max_length=256)),
                ('task_args', models.TextField(blank=True, help_text='任务位置参数（JSON数组格式）', null=True)),
                ('task_kwargs', models.TextField(blank=True, help_text='任务关键字参数（JSON对象格式）', null=True)),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用'), (2, '暂停')], db_index=True, default=0, help_text='任务状态')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='任务优先级')),
                ('max_instances', models.IntegerField(default=1, help_text='最大实例数')),
                ('max_retries', models.IntegerField(default=0, help_text='错误重试次数')),
                ('timeout', models.IntegerField(blank=True, help_text='超时时间（秒）', null=True)),
                ('coalesce', models.BooleanField(default=True, help_text='是否合并执行')),
                ('allow_concurrent', models.BooleanField(default=False, help_text='是否允许并发执行')),
                ('total_run_count', models.IntegerField(default=0, help_text='总执行次数')),
                ('success_count', models.IntegerField(default=0, help_text='成功次数')),
                ('failure_count', models.IntegerField(default=0, help_text='失败次数')),
                ('last_run_time', models.DateTimeField(blank=True, help_text='最后执行时间', null=True)),
                ('next_run_time', models.DateTimeField(blank=True, help_text='下次执行时间', null=True)),
                ('last_run_status', models.CharField(blank=True, help_text='最后执行状态', max_length=20, null=True)),
                ('last_run_result', models.TextField(blank=True, help_text='最后执行结果', null=True)),
                ('remark', models.TextField(blank=True, help_text='备注信息', null=True)),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'db_table': 'core_scheduler_job',
                'ordering': ('-priority', '-sys_update_datetime'),
            },
        ),
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('job_name', models.CharField(db_index=True, help_text='任务名称', max_length=128)),
                ('job_code', models.CharField(db_index=True, help_text='任务编码', max_length=128)),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('timeout', '执行超时'), ('skipped', '跳过执行')], db_index=True, default='pending', help_text='执行状态', max_length=20)),
                ('start_time', models.DateTimeField(db_index=True, help_text='开始时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='结束时间', null=True)),
                ('duration', models.FloatField(blank=True, help_text='执行耗时（秒）', null=True)),
                ('result', models.TextField(blank=True, help_text='执行结果', null=True)),
                ('exception', models.TextField(blank=True, help_text='异常信息', null=True)),
                ('traceback', models.TextField(blank=True, help_text='异常堆栈', null=True)),
                ('hostname', models.CharField(blank=True, help_text='执行主机', max_length=128, null=True)),
                ('process_id', models.IntegerField(blank=True, help_text='进程ID', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='重试次数')),
                ('job', models.ForeignKey(db_constraint=False, help_text='关联的任务', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scheduler.schedulerjob')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '定时任务执行日志',
                'verbose_name_plural': '定时任务执行日志',
                'db_table': 'core_scheduler_log',
                'ordering': ('-start_time',),
            },
        ),
        migrations.AddIndex(
            model_name='schedulerjob',
            index=models.Index(fields=['status', 'trigger_type'], name='core_schedu_status_7002e9_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerjob',
            index=models.Index(fields=['group', 'status'], name='core_schedu_group_139cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerjob',
            index=models.Index(fields=['priority', 'status'], name='core_schedu_priorit_93a1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerjob',
            index=models.Index(fields=['next_run_time', 'status'], name='core_schedu_next_ru_a49d65_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerlog',
            index=models.Index(fields=['job', 'status'], name='core_schedu_job_id_830415_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerlog',
            index=models.Index(fields=['status', 'start_time'], name='core_schedu_status_1e6391_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerlog',
            index=models.Index(fields=['job_code', 'start_time'], name='core_schedu_job_cod_63af46_idx'),
        ),
    ]
