# Generated by Django 5.2.7 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_douyin_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinaccount',
            name='pending_verification_at',
            field=models.DateTimeField(blank=True, help_text='最近一次识别到验证页的时间', null=True),
        ),
        migrations.AddField(
            model_name='douyinaccount',
            name='pending_verification_type',
            field=models.CharField(blank=True, choices=[('sms', '短信验证'), ('face', '人脸验证'), ('captcha', '验证码校验'), ('security', '安全验证'), ('unknown', '待人工确认')], db_index=True, help_text='待人工完成的验证类型', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='douyinaccount',
            name='pending_verification_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='人工验证冷却截止时间；在此之前 worker 不自动重登', null=True),
        ),
    ]
