# Generated by Django 5.2.7 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_douyin_account_pending_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinaccount',
            name='last_history_sync_at',
            field=models.DateTimeField(blank=True, help_text='最近一次历史会话补扫完成时间', null=True),
        ),
    ]
