# Generated by Django 5.2.7 on 2026-04-24 00:00

from django.db import migrations


def hide_quick_reply_menu(apps, schema_editor):
    Menu = apps.get_model('core', 'Menu')
    Menu.objects.filter(path='/douyin/quick-reply').update(
        hideInMenu=True,
        hideInBreadcrumb=True,
        hideInTab=True,
    )


def show_quick_reply_menu(apps, schema_editor):
    Menu = apps.get_model('core', 'Menu')
    Menu.objects.filter(path='/douyin/quick-reply').update(
        hideInMenu=False,
        hideInBreadcrumb=False,
        hideInTab=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_douyin_account_history_sync'),
    ]

    operations = [
        migrations.RunPython(hide_quick_reply_menu, show_quick_reply_menu),
    ]
