# Generated by Django 5.2.7 on 2026-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hide_quick_reply_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinaccount',
            name='auto_reply_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='是否启用自动回复'),
        ),
    ]
