# Generated by Django 5.2.7 on 2026-06-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_kuaishou_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='douyinevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', '登录成功'), ('login_expired', '登录失效'), ('qr_generated', '二维码生成'), ('qr_scanned', '已扫码'), ('worker_started', 'Worker 启动'), ('worker_stopped', 'Worker 停止'), ('session_paused', '会话暂停'), ('session_resumed', '会话恢复'), ('message_received', '收到消息'), ('reply_sent', '已发送回复'), ('reply_failed', '回复失败'), ('reply_skipped', '跳过回复'), ('risk_alert', '风控告警'), ('rate_limit', '触发限流'), ('quota_exceeded', '配额超限'), ('blacklist_hit', '命中黑名单'), ('identity_mismatch', '账号身份漂移'), ('unknown_error', '未知异常')], db_index=True, help_text='事件类型', max_length=32),
        ),
    ]
