# Generated by Django 5.2.7 on 2026-06-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_douyinevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinaccount',
            name='credential_state',
            field=models.CharField(choices=[('unknown', '未知'), ('sendable', '可发送'), ('receive_only', '仅接收'), ('invalid', '已失效')], db_index=True, default='unknown', help_text='凭证能力分级（可发送/仅接收/已失效），由探活与录入更新', max_length=16),
        ),
        migrations.AddField(
            model_name='douyinaccount',
            name='last_probe_at',
            field=models.DateTimeField(blank=True, help_text='最近一次凭证探活时间', null=True),
        ),
        migrations.AddField(
            model_name='douyinaccount',
            name='last_probe_error',
            field=models.CharField(blank=True, help_text='最近一次探活/请求失败原因（用于面板标红与排障）', max_length=255, null=True),
        ),
    ]
