# Generated by Django 5.2.7 on 2026-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_douyinaccount_credential_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='douyinsession',
            name='context_id',
            field=models.CharField(help_text='会话运行时标识（纯 HTTP 协议下为 ctx_<account 前缀>，保留字段兼容历史）', max_length=64),
        ),
    ]
