# Generated by Claude Code

from django.db import migrations
import uuid


def add_message_reply_menu_and_permission(apps, schema_editor):
    """添加消息回复菜单和权限"""
    Menu = apps.get_model('core', 'Menu')
    Permission = apps.get_model('core', 'Permission')

    # 找到抖音中心的父菜单（DouyinCenter）
    douyin_parent = Menu.objects.filter(
        path='/douyin',
        is_deleted=False
    ).first()

    if not douyin_parent:
        print("警告: 未找到抖音父菜单，跳过菜单创建")
        return

    # 检查是否已存在
    existing_menu = Menu.objects.filter(
        path='/douyin/message-reply',
        is_deleted=False
    ).first()

    if existing_menu:
        print(f"✓ 菜单已存在: 消息回复 (ID: {existing_menu.id})")
        created_menu = existing_menu
    else:
        # 创建消息回复菜单
        menu_id = str(uuid.uuid4())
        created_menu = Menu.objects.create(
            id=menu_id,
            name='DouyinMessageReply',
            title='消息回复',
            path='/douyin/message-reply',
            component='views/douyin/message-reply/index.vue',
            parent=douyin_parent,
            type='menu',
            icon='mdi:message-reply-text',
            order=15,
            hideInMenu=False,
            is_deleted=False,
        )
        print(f"✓ 已创建菜单: 消息回复 (ID: {menu_id})")

    # 检查权限是否已存在
    existing_perm = Permission.objects.filter(
        code='douyin:message-reply:view',
        is_deleted=False
    ).first()

    if existing_perm:
        print(f"✓ 权限已存在: 抖音消息回复 (ID: {existing_perm.id})")
    else:
        # 创建消息回复权限，关联到菜单
        permission_id = str(uuid.uuid4())
        Permission.objects.create(
            id=permission_id,
            name='抖音消息回复',
            code='douyin:message-reply:view',
            permission_type=1,  # 1 表示菜单权限
            menu=created_menu,  # 关联到菜单
            is_active=True,
            is_deleted=False,
        )
        print(f"✓ 已创建权限: 抖音消息回复 (ID: {permission_id}, code: douyin:message-reply:view)")


def reverse_message_reply_menu_and_permission(apps, schema_editor):
    """回滚：删除消息回复菜单和权限"""
    Menu = apps.get_model('core', 'Menu')
    Permission = apps.get_model('core', 'Permission')

    # 删除菜单
    deleted_menus = Menu.objects.filter(
        path='/douyin/message-reply',
        is_deleted=False
    ).update(is_deleted=True)
    print(f"✓ 已删除 {deleted_menus} 个菜单")

    # 删除权限
    deleted_perms = Permission.objects.filter(
        code='douyin:message-reply:view',
        is_deleted=False
    ).update(is_deleted=True)
    print(f"✓ 已删除 {deleted_perms} 个权限")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_douyinsession_context_id'),
    ]

    operations = [
        migrations.RunPython(
            add_message_reply_menu_and_permission,
            reverse_message_reply_menu_and_permission
        ),
    ]
