# Generated by Django 5.2.7 on 2026-06-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_normalize_douyinaccount_sec_uid_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='软删除时间戳（用于 7 天保留期重复检测）', null=True),
        ),
    ]
