# Generated by Django 5.2.7 on 2026-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_deleted_at_to_douyin_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinaccount',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='抖音号（unique_id，用户自定义ID）', max_length=64, null=True),
        ),
    ]
