# Generated by Django 5.2.7 on 2026-06-18 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_douyin_conversation_peer_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('device_fingerprint', models.CharField(db_index=True, help_text='设备指纹', max_length=128, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='设备名称', max_length=128, null=True)),
                ('os_type', models.CharField(blank=True, db_index=True, help_text='系统类型', max_length=32, null=True)),
                ('os_version', models.CharField(blank=True, help_text='系统版本', max_length=64, null=True)),
                ('app_version', models.CharField(blank=True, help_text='客户端版本', max_length=64, null=True)),
                ('machine_meta', models.JSONField(blank=True, default=dict, help_text='设备元信息')),
                ('first_seen_at', models.DateTimeField(blank=True, help_text='首次出现时间', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, help_text='最后出现时间', null=True)),
                ('status', models.CharField(choices=[('active', '活跃'), ('blocked', '已封禁')], db_index=True, default='active', help_text='设备状态', max_length=16)),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_client_device',
                'ordering': ('-last_seen_at', '-sys_create_datetime'),
            },
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('code_hash', models.CharField(db_index=True, help_text='卡密哈希', max_length=64, unique=True)),
                ('masked_code', models.CharField(db_index=True, help_text='脱敏卡密', max_length=64)),
                ('status', models.CharField(choices=[('pending', '未激活'), ('active', '生效中'), ('revoked', '已撤销'), ('expired', '已过期')], db_index=True, default='pending', help_text='授权状态', max_length=16)),
                ('issued_to', models.CharField(blank=True, help_text='发放对象', max_length=128, null=True)),
                ('batch_no', models.CharField(blank=True, db_index=True, help_text='批次号', max_length=64, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='到期时间', null=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='首次激活时间', null=True)),
                ('last_check_in_at', models.DateTimeField(blank=True, db_index=True, help_text='最后心跳时间', null=True)),
                ('max_devices_override', models.IntegerField(blank=True, help_text='设备数覆盖', null=True)),
                ('valid_days_override', models.IntegerField(blank=True, help_text='有效天数覆盖', null=True)),
                ('notes', models.TextField(blank=True, help_text='备注', null=True)),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_license_key',
                'ordering': ('-sys_create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('activation_token_hash', models.CharField(db_index=True, help_text='激活令牌哈希', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', '活跃'), ('revoked', '已撤销'), ('deactivated', '已解绑'), ('expired', '已过期')], db_index=True, default='active', help_text='激活状态', max_length=16)),
                ('activated_at', models.DateTimeField(help_text='激活时间')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='到期时间', null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, help_text='最后心跳时间', null=True)),
                ('last_valid_until', models.DateTimeField(blank=True, db_index=True, help_text='离线可用截止', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='撤销时间', null=True)),
                ('revoked_reason', models.CharField(blank=True, help_text='撤销原因', max_length=255, null=True)),
                ('client_device', models.ForeignKey(db_constraint=False, help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.clientdevice')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('license_key', models.ForeignKey(db_constraint=False, help_text='关联卡密', on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.licensekey')),
            ],
            options={
                'db_table': 'core_license_activation',
                'ordering': ('-activated_at',),
            },
        ),
        migrations.CreateModel(
            name='LicensePlan',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('code', models.CharField(db_index=True, help_text='套餐编码', max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, help_text='套餐名称', max_length=128)),
                ('description', models.TextField(blank=True, help_text='套餐描述', null=True)),
                ('feature_flags', models.JSONField(blank=True, default=dict, help_text='功能开关')),
                ('max_devices', models.IntegerField(default=1, help_text='最大设备数')),
                ('valid_days', models.IntegerField(default=365, help_text='默认有效天数，0 表示不按天数限制')),
                ('heartbeat_interval_minutes', models.IntegerField(default=30, help_text='心跳间隔分钟')),
                ('grace_period_minutes', models.IntegerField(default=2880, help_text='离线宽限期分钟')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_license_plan',
                'ordering': ('sort', '-sys_create_datetime'),
            },
        ),
        migrations.AddField(
            model_name='licensekey',
            name='plan',
            field=models.ForeignKey(db_constraint=False, help_text='授权套餐', on_delete=django.db.models.deletion.PROTECT, related_name='license_keys', to='core.licenseplan'),
        ),
        migrations.CreateModel(
            name='LicenseEvent',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('event_type', models.CharField(db_index=True, help_text='事件类型', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='事件载荷')),
                ('ip', models.CharField(blank=True, help_text='来源 IP', max_length=64, null=True)),
                ('activation', models.ForeignKey(blank=True, db_constraint=False, help_text='关联激活', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.licenseactivation')),
                ('client_device', models.ForeignKey(blank=True, db_constraint=False, help_text='关联设备', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.clientdevice')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('license_key', models.ForeignKey(blank=True, db_constraint=False, help_text='关联卡密', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.licensekey')),
            ],
            options={
                'db_table': 'core_license_event',
                'ordering': ('-sys_create_datetime',),
                'indexes': [models.Index(fields=['event_type', 'sys_create_datetime'], name='core_licens_event_t_9668e8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='licenseactivation',
            index=models.Index(fields=['license_key', 'status'], name='core_licens_license_ccfca6_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseactivation',
            index=models.Index(fields=['client_device', 'status'], name='core_licens_client__193fc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='licenseactivation',
            unique_together={('license_key', 'client_device')},
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['status', 'plan'], name='core_licens_status_bcc3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['expires_at', 'status'], name='core_licens_expires_e83fae_idx'),
        ),
    ]
