# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_seed_license_event_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseactivation",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, help_text="当前租约到期时间", null=True),
        ),
        migrations.AddField(
            model_name="licenseactivation",
            name="lease_refresh_token_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="续签令牌哈希",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="licenseactivation",
            name="lease_sequence",
            field=models.IntegerField(default=0, help_text="租约版本序号"),
        ),
    ]
