# Generated by Django 5.2.7 on 2026-06-24 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_license_activation_lease_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAnnouncement',
            fields=[
                ('id', models.CharField(editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('level', models.CharField(choices=[('info', '普通'), ('warning', '警告'), ('urgent', '紧急')], default='info', max_length=20, verbose_name='公告级别')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('revoked', '已撤回')], default='draft', max_length=20, verbose_name='状态')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('target_version', models.CharField(blank=True, help_text='留空表示所有版本，支持版本范围如 >=0.1.10', max_length=50, null=True, verbose_name='目标客户端版本')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '客户端公告',
                'verbose_name_plural': '客户端公告',
                'db_table': 'core_client_announcement',
                'ordering': ['-publish_time', '-sys_create_datetime'],
            },
        ),
    ]
