# Generated by Django 5.2.7 on 2026-06-24 18:58

import common.fu_model
import core.client_announcement.client_announcement_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_douyin_rule_account_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinaccount',
            name='aweme_count',
            field=models.BigIntegerField(default=0, help_text='作品数（缓存）'),
        ),
        migrations.AddField(
            model_name='douyinaccount',
            name='follower_count',
            field=models.BigIntegerField(default=0, help_text='粉丝数（缓存）'),
        ),
        migrations.AddField(
            model_name='douyinaccount',
            name='following_count',
            field=models.BigIntegerField(default=0, help_text='关注数（缓存）'),
        ),
        migrations.AddField(
            model_name='douyinaccount',
            name='last_profile_sync_at',
            field=models.DateTimeField(blank=True, help_text='最近一次主页统计同步时间', null=True),
        ),
        migrations.AddField(
            model_name='douyinaccount',
            name='total_favorited',
            field=models.BigIntegerField(default=0, help_text='获赞总数（缓存）'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='announcementread',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientannouncement',
            name='id',
            field=models.CharField(default=core.client_announcement.client_announcement_model.generate_uuid, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dept',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dict',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dictitem',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinaccount',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinaccountgroup',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinblacklist',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinconversation',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyindailystat',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', '登录成功'), ('login_expired', '登录失效'), ('qr_generated', '二维码生成'), ('qr_scanned', '已扫码'), ('worker_started', 'Worker 启动'), ('worker_stopped', 'Worker 停止'), ('session_paused', '会话暂停'), ('session_resumed', '会话恢复'), ('message_received', '收到消息'), ('ws_connected', 'WS已连接'), ('ws_disconnected', 'WS断开'), ('ws_skipped', 'WS未启用(跳过)'), ('reply_sent', '已发送回复'), ('reply_failed', '回复失败'), ('reply_skipped', '跳过回复'), ('risk_alert', '风控告警'), ('rate_limit', '触发限流'), ('quota_exceeded', '配额超限'), ('blacklist_hit', '命中黑名单'), ('identity_mismatch', '账号身份漂移'), ('unknown_error', '未知异常')], db_index=True, help_text='事件类型', max_length=32),
        ),
        migrations.AlterField(
            model_name='douyinevent',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinmessage',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinquickreply',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinreplylog',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinrule',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='[已弃用] 旧单账号绑定字段；保留兼容，实际绑定见 account_ids', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.douyinaccount'),
        ),
        migrations.AlterField(
            model_name='douyinrule',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinsession',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyintemplate',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyintemplatecategory',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='douyinworkercommand',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filemanager',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kuaishouaccount',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kuaishouaccountgroup',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kuaishouconversation',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kuaishoudailystat',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kuaishouevent',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kuaishoumessage',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kuaishoureplylog',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kuaishousession',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licenseactivation',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licenseevent',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licenseplan',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quickreply',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='replyrule',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='replytemplate',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='replytemplatecategory',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False),
        ),
    ]
