# Generated by Django 5.2.7 on 2026-06-26 13:02

import common.fu_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_douyinaccount_aweme_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinrule',
            name='card_ids',
            field=models.JSONField(blank=True, default=list, help_text='关联的伪装卡片 ID 列表；命中后按顺序各发一条卡片落地页 URL'),
        ),
        migrations.CreateModel(
            name='DouyinCard',
            fields=[
                ('id', models.CharField(default=common.fu_model.gen_uuid_str, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('title', models.CharField(db_index=True, help_text='卡片标题（→ og:title）', max_length=200)),
                ('description', models.CharField(blank=True, default='', help_text='卡片描述/副标题（→ og:description）', max_length=500)),
                ('cover_file_id', models.CharField(blank=True, help_text='封面图，file_manager 文件 UUID 软引用（→ og:image）', max_length=64, null=True)),
                ('target_url', models.CharField(help_text='真实跳转链接，落地页 302 跳转目标（仅 http/https）', max_length=1000)),
                ('remark', models.CharField(blank=True, help_text='备注（后台展示用）', max_length=255, null=True)),
                ('status', models.BooleanField(db_index=True, default=True, help_text='是否启用')),
                ('is_shared', models.BooleanField(default=False, help_text='是否跨用户共享（预留，沿用模板范式）')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, help_text='创建者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='douyin_cards', to=settings.AUTH_USER_MODEL)),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '抖音伪装卡片',
                'verbose_name_plural': '抖音伪装卡片',
                'db_table': 'core_douyin_card',
                'ordering': ('-sort', '-sys_create_datetime'),
                'indexes': [models.Index(fields=['owner', 'status'], name='core_douyin_owner_i_952376_idx')],
            },
        ),
    ]
