# Generated by Django 5.2.7 on 2026-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_seed_douyin_card_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyincard',
            name='source_activation_id',
            field=models.CharField(blank=True, help_text='同步来源 license 激活 id（公网侧记录）', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='douyincard',
            name='source_device_id',
            field=models.CharField(blank=True, db_index=True, help_text='同步来源客户端设备指纹/ClientDevice id（公网侧记录；客户端本地为空）', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='douyincard',
            name='sync_state',
            field=models.CharField(default='local', help_text='同步状态：local(本地无需同步)/pending/synced/failed（客户端侧使用）', max_length=16),
        ),
    ]
