# Generated by Django 5.2.7 on 2026-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_douyincard_source_activation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinconversation',
            name='platform_conversation_short_id',
            field=models.BigIntegerField(blank=True, help_text='抖音平台侧 conversation_short_id（发送协议路由使用）', null=True),
        ),
        migrations.AddField(
            model_name='douyinconversation',
            name='platform_conversation_ticket',
            field=models.CharField(blank=True, help_text='抖音平台侧会话 ticket（仅服务端发送协议使用）', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='douyinconversation',
            name='platform_conversation_ticket_updated_at',
            field=models.DateTimeField(blank=True, help_text='会话 ticket 最近成功刷新时间', null=True),
        ),
        migrations.AddIndex(
            model_name='douyinconversation',
            index=models.Index(fields=['account', 'platform_conversation_id'], name='dy_conv_acc_platform_idx'),
        ),
    ]
