# Generated by Django 5.2.7 on 2026-09-05 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_douyinworkercommand_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='agent_fence_counter',
            field=models.PositiveBigIntegerField(db_default=0, default=0, help_text='账号租约全局递增 fencing 序号'),
        ),
        migrations.CreateModel(
            name='AgentAccountLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(default='douyin', max_length=16)),
                ('platform_account_id', models.CharField(max_length=256)),
                ('local_account_id', models.CharField(max_length=256)),
                ('owner_instance_id', models.UUIDField()),
                ('owner_boot_id', models.UUIDField()),
                ('fence_epoch', models.PositiveBigIntegerField()),
                ('lease_until', models.DateTimeField(db_index=True)),
                ('released', models.BooleanField(default=False)),
                ('license_key', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='core.licensekey')),
                ('owner_activation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='core.licenseactivation')),
            ],
            options={
                'db_table': 'core_agent_account_lease',
                'indexes': [models.Index(fields=['license_key', 'lease_until'], name='agent_lease_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('license_key', 'platform', 'platform_account_id'), name='agent_lease_platform_unique')],
            },
        ),
        migrations.CreateModel(
            name='AgentSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.UUIDField()),
                ('boot_id', models.UUIDField()),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('request_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('response_claims', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('activation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='core.licenseactivation')),
            ],
            options={
                'db_table': 'core_agent_sync_state',
                'constraints': [models.UniqueConstraint(fields=('activation', 'instance_id', 'boot_id'), name='agent_sync_boot_unique')],
            },
        ),
    ]
